name: Deploy Prod

on:
    workflow_run:
        workflows: ["Deploy Staging"]
        types:
            - completed

jobs:
    deploy-prod:
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        environment: prod
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: environments/prod
        permissions:
            id-token: write
            contents: read
        steps:
            - name: pr-checks
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: OIDC Authentication
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: us-east-1

            - name: Terraform Init
              run: terraform init

            - name: Terraform Apply
              run: terraform apply -auto-approve
