name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: pr-checks
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: OIDC Authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PR_CHECKS }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: tfsec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Checkov Security Scan
        uses: bridgecrewio/checkov-action@master

      - name: Terraform Plan
        run: terraform plan
